Using the Kronecker product and the np.kron function in numpy (we are using it as an example, but you can use any library you want to), you can create a vector of length 2^n representing an n-qubit quantum state, and matrix representation of X, H, and CNOT gates.

In [12]:
import numpy as np

a = np.arange(60.)
print(a,'\n') # a = [ [ [ x x x x x ],[],[],[]  ], [], [] ]
a = np.arange(60.).reshape(3,4,5)
print(a)

b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))

print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59.] 

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]
[[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]


In [34]:
N = 3

ket_zero = np.array([1,0])
ket_one = np.array([0,1])

three_qubit_state = np.kron(ket_zero, np.kron(ket_zero, ket_zero))

print(three_qubit_state)

state = three_qubit_state.reshape(4,2)
print(state)

[1 0 0 0 0 0 0 0]
[[1 0]
 [0 0]
 [0 0]
 [0 0]]


In [23]:
a = state.reshape(2,2)
print(a)

[[0 0]
 [0 1]]
