Using the Kronecker product and the np.kron function in numpy (we are using it as an example, but you can use any library you want to), you can create a vector of length 2^n representing an n-qubit quantum state, and matrix representation of X, H, and CNOT gates.

In [2]:
import numpy as np

a = np.arange(60.)
print(a,'\n') # a = [ [ [ x x x x x ],[],[],[]  ], [], [] ]
a = np.arange(60.).reshape(3,4,5)
print(a)

b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))

print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59.] 

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]
[[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]


In [3]:
N = 3

ket_zero = np.array([1,0])
ket_one = np.array([0,1])

three_qubit_state = np.kron(ket_zero, np.kron(ket_zero, ket_zero))

print(three_qubit_state)

state = three_qubit_state.reshape(4,2)
print(state)

[1 0 0 0 0 0 0 0]
[[1 0]
 [0 0]
 [0 0]
 [0 0]]


In [5]:
# a = state.reshape(2,2)
# print(a)

In [7]:
H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])
H

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [29]:
import numpy as np

# Define basis gate (computational)
zero = np.array([1,0])
one = np.array([0,1])


# Define ket 0 state
state = np.tensordot(zero, one, axes=0)
print(state)


# Define 1-qubit quantum gate
H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])
X = np.array([[0,1],[1,0]])


updated_state = np.tensordot(state, H, axes=([0], [0]))
print("\nUpdated State:")
print(updated_state)


updated_state_2 = np.tensordot(updated_state, X, axes=([0], [0]))
print("\nUpdated State:")
print(updated_state_2)

[[0 1]
 [0 0]]

Updated State:
[[0.         0.        ]
 [0.70710678 0.70710678]]

Updated State:
[[0.70710678 0.        ]
 [0.70710678 0.        ]]


In [23]:
state = np.tensordot(np.tensordot(zero, zero, axes=0), one, axes=0)
print(state)

updated_state = np.tensordot(state, H, axes=([0],[0]))
print(updated_state)

[[[0 1]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[0.         0.        ]
  [0.70710678 0.70710678]]

 [[0.         0.        ]
  [0.         0.        ]]]


In [25]:
psi = np.array([0,1,0,0]).reshape(2,2)
psi

array([[0, 1],
       [0, 0]])

In [27]:
result = np.tensordot(X, psi, axes=(1, 0))
result

array([[0, 0],
       [0, 1]])

In [28]:
result = np.tensordot(psi, X, axes=(1, 0))
result

array([[1, 0],
       [0, 0]])

# Three Qubit

In [46]:
tqs = np.tensordot(np.tensordot(zero, zero, axes=0), one, axes=0)
tqs

array([[[0, 1],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [53]:
import numpy as np

# Define the basis states for a single qubit
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

# Define a function to compute the tensor product for n qubits
def tensor_product(*kets):
    result = kets[0]
    for ket in kets[1:]:
        result = np.tensordot(result, ket, axes=0)
        # result = result.flatten()  # Flatten to maintain a 1D array
    return result

# Example: Create the state |000⟩
tqs = tensor_product(ket_0, ket_0, ket_1)

# Print the result
print("Three-qubit state |000⟩:")
tqs

Three-qubit state |000⟩:


array([[[0, 1],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

Apply to the first qubit

In [54]:
tqs_2 = tensor_product(ket_1, ket_0, ket_1)
tqs_2

array([[[0, 0],
        [0, 0]],

       [[0, 1],
        [0, 0]]])

In [66]:
new_state = np.tensordot(X, tqs, axes=([1],[0]))
print(new_state)

[[[0 0]
  [0 0]]

 [[0 1]
  [0 0]]]


Apply to the second qubit

In [64]:
new_state = np.tensordot(tqs, X, axes=([1],[0]))
print(new_state)

[[[0 0]
  [0 1]]

 [[0 0]
  [0 0]]]


In [57]:
tqs_3 = tensor_product(ket_0, ket_1, ket_1)
tqs_3

array([[[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 0]]])

Apply to the third qubit

In [59]:
new_state = np.tensordot(tqs, X, axes=([2], [0]))
print(new_state)

[[[1 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [60]:
tqs_4 = tensor_product(ket_0, ket_0, ket_0)
tqs_4

array([[[1, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])