Using the Kronecker product and the np.kron function in numpy (we are using it as an example, but you can use any library you want to), you can create a vector of length 2^n representing an n-qubit quantum state, and matrix representation of X, H, and CNOT gates.

In [2]:
import numpy as np

a = np.arange(60.)
print(a,'\n') # a = [ [ [ x x x x x ],[],[],[]  ], [], [] ]
a = np.arange(60.).reshape(3,4,5)
print(a)

b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))

print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59.] 

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]
[[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]


In [3]:
N = 3

ket_zero = np.array([1,0])
ket_one = np.array([0,1])

three_qubit_state = np.kron(ket_zero, np.kron(ket_zero, ket_zero))

print(three_qubit_state)

state = three_qubit_state.reshape(4,2)
print(state)

[1 0 0 0 0 0 0 0]
[[1 0]
 [0 0]
 [0 0]
 [0 0]]


In [5]:
# a = state.reshape(2,2)
# print(a)

In [7]:
H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])
H

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [29]:
import numpy as np

# Define basis gate (computational)
zero = np.array([1,0])
one = np.array([0,1])


# Define ket 0 state
state = np.tensordot(zero, one, axes=0)
print(state)


# Define 1-qubit quantum gate
H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])
X = np.array([[0,1],[1,0]])


updated_state = np.tensordot(state, H, axes=([0], [0]))
print("\nUpdated State:")
print(updated_state)


updated_state_2 = np.tensordot(updated_state, X, axes=([0], [0]))
print("\nUpdated State:")
print(updated_state_2)

[[0 1]
 [0 0]]

Updated State:
[[0.         0.        ]
 [0.70710678 0.70710678]]

Updated State:
[[0.70710678 0.        ]
 [0.70710678 0.        ]]


In [23]:
state = np.tensordot(np.tensordot(zero, zero, axes=0), one, axes=0)
print(state)

updated_state = np.tensordot(state, H, axes=([0],[0]))
print(updated_state)

[[[0 1]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[0.         0.        ]
  [0.70710678 0.70710678]]

 [[0.         0.        ]
  [0.         0.        ]]]


In [25]:
psi = np.array([0,1,0,0]).reshape(2,2)
psi

array([[0, 1],
       [0, 0]])

In [27]:
result = np.tensordot(X, psi, axes=(1, 0))
result

array([[0, 0],
       [0, 1]])

In [28]:
result = np.tensordot(psi, X, axes=(1, 0))
result

array([[1, 0],
       [0, 0]])

# Three Qubit

In [46]:
tqs = np.tensordot(np.tensordot(zero, zero, axes=0), one, axes=0)
tqs

array([[[0, 1],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [99]:
import numpy as np

# Define the basis states for a single qubit
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

# Define a function to compute the tensor product for n qubits
def tensor_product(*kets):
    result = kets[0]
    for ket in kets[1:]:
        result = np.tensordot(result, ket, axes=0)
        # result = result.flatten()  # Flatten to maintain a 1D array
    return result

# Example: Create the state |000⟩
tqs = tensor_product(ket_1, ket_1, ket_1)

# Print the result
print("Three-qubit state: ")
tqs

Three-qubit state: 


array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1]]])

Apply to the first qubit

In [101]:
tqs_2 = tensor_product(ket_0, ket_1, ket_1)
tqs_2

array([[[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 0]]])

In [108]:
tensor_product(ket_0, ket_1, ket_1)

array([[[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 0]]])

In [103]:
new_state = np.tensordot(X, tqs, axes=([1],[0]))
print('X:', X, '\n')
print('tqs:', tqs, '\n')
print('state:', new_state)

X: [[0 1]
 [1 0]] 

tqs: [[[0 0]
  [0 0]]

 [[0 0]
  [0 1]]] 

state: [[[0 0]
  [0 1]]

 [[0 0]
  [0 0]]]


Apply to the second qubit

In [64]:
new_state = np.tensordot(tqs, X, axes=([1],[0]))
print(new_state)

[[[0 0]
  [0 1]]

 [[0 0]
  [0 0]]]


In [57]:
tqs_3 = tensor_product(ket_0, ket_1, ket_1)
tqs_3

array([[[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 0]]])

Apply to the third qubit

In [59]:
new_state = np.tensordot(tqs, X, axes=([2], [0]))
print(new_state)

[[[1 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [60]:
tqs_4 = tensor_product(ket_0, ket_0, ket_0)
tqs_4

array([[[1, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

### Representation of 3D tensor

initial state

In [74]:
import numpy as np

# Initial state |000⟩ represented as a tensor of shape (2, 2, 2)
# The tensor has dimensions: (First Qubit, Second Qubit, Third Qubit)
# The state |000⟩ means all qubits are in the |0⟩ state.

# Initialize the tensor with zeros
reshaped_state = np.zeros((2, 2, 2))
print(reshaped_state)

# Set the |000⟩ state to 1
reshaped_state[0, 0, 0] = 1  # This corresponds to |000⟩

print('\n', reshaped_state)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

 [[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


apply X to the first qubit

In [70]:
# Define the X gate
X_gate = np.array([[0, 1], [1, 0]])  # X gate flips |0⟩ to |1⟩ and |1⟩ to |0⟩

# Apply X gate to the first qubit
new_state_first = np.tensordot(reshaped_state, X_gate, axes=([0], [0]))

print("State after applying X to first qubit:")
print(new_state_first)


State after applying X to first qubit:
[[[0. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


apply X to the second qubit

In [81]:
# Apply X gate to the second qubit
new_state_second = np.tensordot(X_gate, new_state_first, axes=([1], [0]))

print("State after applying X to second qubit:")
print(new_state_second)


State after applying X to second qubit:
[[[0. 0.]
  [0. 0.]]

 [[0. 1.]
  [0. 0.]]]


apply X to the third qubit

In [90]:
# Apply X gate to the third qubit
new_state_third = np.tensordot(new_state_second, X_gate, axes=([1], [0]))

print("State after applying X to third qubit:")
print(new_state_third)

State after applying X to third qubit:
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]


N qubit state

In [92]:
import numpy as np

# Define the X gate (NOT gate)
X = np.array([[0, 1], [1, 0]])

def apply_x_gate_with_tensordot(state, qubit_index):
    # Total number of qubits
    N = int(np.log2(state.size))
    
    # Reshape state into an N-dimensional array
    state_reshaped = state.reshape([2] * N)
    
    # Create an identity matrix for other qubits
    identity = np.eye(2)
    
    # Create a list of operators: X for the target qubit, identity for others
    operators = [identity] * N
    operators[qubit_index] = X
    
    # Combine operators using tensordot
    combined_operator = operators[0]
    for op in operators[1:]:
        combined_operator = np.tensordot(combined_operator, op, axes=0)

    # Reshape the combined operator for multiplication
    combined_operator = combined_operator.reshape((2**N, 2**N))
    
    # Apply the combined operator to the state
    new_state = np.dot(combined_operator, state)
    
    return new_state

# Define a sample N-qubit state |000...0> for N=3
N = 2
initial_state = np.zeros(2 ** N)
initial_state[0] = 1  # |000> state

# Apply the X gate to the first qubit (qubit_index = 0)
new_state = apply_x_gate_with_tensordot(initial_state, 0)

print("Initial state:", initial_state)
print("New state after applying X gate to qubit 0:", new_state)


Initial state: [1. 0. 0. 0.]
New state after applying X gate to qubit 0: [0. 1. 1. 0.]


In [93]:
import numpy as np

# Define the 1-qubit gates
X = np.array([[0, 1],
              [1, 0]])  # X gate (NOT)

H = (1/np.sqrt(2)) * np.array([[1, 1],
                                [1, -1]])  # Hadamard gate

# Define the 2-qubit gate: CNOT (control on first qubit)
CNOT = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])  # CNOT gate

# Function to create an initial state (e.g., |00..0>)
def create_initial_state(n):
    return np.zeros((2,) * n)  # Tensor of shape (2, 2, ..., 2) for n qubits

# Function to apply a gate
def apply_gate(state_tensor, gate_matrix, qubit_index):
    # Reshape state tensor to match the gate for the specified qubit
    new_shape = list(state_tensor.shape)
    new_shape[qubit_index] = gate_matrix.shape[0]
    reshaped_state = state_tensor.reshape(new_shape)
    
    # Apply the gate using tensordot
    result = np.tensordot(gate_matrix, reshaped_state, axes=([1], [qubit_index]))
    
    # Reshape back to the original tensor shape
    result_shape = list(state_tensor.shape)
    result_shape[qubit_index] = gate_matrix.shape[0]
    return result.reshape(result_shape)

# Function to apply a 2-qubit gate
def apply_two_qubit_gate(state_tensor, gate_matrix, control_qubit, target_qubit):
    # Reshape state tensor
    new_shape = list(state_tensor.shape)
    new_shape[control_qubit] = gate_matrix.shape[0]
    new_shape[target_qubit] = gate_matrix.shape[1]
    
    reshaped_state = state_tensor.reshape(new_shape)
    
    # Apply the CNOT gate
    result = np.tensordot(gate_matrix, reshaped_state, axes=([1, 0], [control_qubit, target_qubit]))
    
    # Reshape back to the original tensor shape
    result_shape = list(state_tensor.shape)
    result_shape[control_qubit] = gate_matrix.shape[0]
    result_shape[target_qubit] = gate_matrix.shape[1]
    return result.reshape(result_shape)

# Main quantum circuit implementation
def quantum_circuit(n):
    # Step 1: Initialize the state |0...0>
    state = create_initial_state(n)
    state[tuple([0] * n)] = 1  # Set initial state |000...0>

    print("Initial State Tensor:")
    print(state)

    # Step 2: Apply H gate to the first qubit
    state = apply_gate(state, H, 0)
    print("State after applying H gate on qubit 0:")
    print(state)

    # Step 3: Apply X gate to the second qubit
    state = apply_gate(state, X, 1)
    print("State after applying X gate on qubit 1:")
    print(state)

    # Step 4: Apply CNOT gate (control qubit 0, target qubit 1)
    state = apply_two_qubit_gate(state, CNOT, 0, 1)
    print("State after applying CNOT (control: qubit 0, target: qubit 1):")
    print(state)

# Run the quantum circuit for 2 qubits
quantum_circuit(2)


Initial State Tensor:
[[1. 0.]
 [0. 0.]]
State after applying H gate on qubit 0:
[[0.70710678 0.        ]
 [0.70710678 0.        ]]
State after applying X gate on qubit 1:
[[0.         0.        ]
 [0.70710678 0.70710678]]


ValueError: cannot reshape array of size 4 into shape (4,4)