### States

Define 
$$
|\psi\rangle = \frac{ | 0000 \rangle + | 1111 \rangle }{\sqrt{2}}
$$

In [12]:
import numpy as np

psi = np.zeros((2,2))
psi[0,0] = 1
psi

array([[1., 0.],
       [0., 0.]])

### Single qubit operators

In [17]:
H_gate = 1/np.sqrt(2)*np.array([[1,1],
                            [1,-1]])

X_gate = np.array([[0,1],
                    [1,0]])

print(H_gate)
print(X_gate)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[[0 1]
 [1 0]]


apply to the first qubit

In [19]:
psi_updated = np.tensordot(X_gate, psi, (1,0))
psi_updated

array([[0., 0.],
       [1., 0.]])

apply to the second qubit

In [20]:
psi_updated_2 = np.tensordot(X_gate, psi, (1,1))
psi_updated_2 = np.moveaxis(psi_updated_2, 0, 1)
psi_updated_2

array([[0., 1.],
       [0., 0.]])

### Example for two-qubit operators

In [28]:
CNOT_gate = np.array([[1,0,0,0],
                    [0,1,0,0],
                    [0,0,0,1],
                    [0,0,1,0]]).reshape(2,2,2,2)
CNOT_gate

array([[[[1, 0],
         [0, 0]],

        [[0, 1],
         [0, 0]]],


       [[[0, 0],
         [0, 1]],

        [[0, 0],
         [1, 0]]]])

In [33]:
psi = np.zeros((2,2))
psi[1,0] = 1
print(psi)

psi_updated_3 = np.tensordot(CNOT_gate, psi, ((2,3), (0,1)))
psi_updated_3 = np.moveaxis(psi_updated_3, (0,1), (0,1))
psi_updated_3

[[0. 0.]
 [1. 0.]]


array([[0., 0.],
       [0., 1.]])