### Import Library

In [1]:
import numpy as np

### Statevectors

In [2]:
ket_0 = np.array([1,0])
ket_1 = np.array([0,1])

### Quantum gates

In [3]:
gate_X = np.array([[0,1], [1,0]])

In [4]:
gate_X

array([[0, 1],
       [1, 0]])

In [5]:
print(gate_X @ ket_0)

[0 1]


### n-qubit quantum state

In [6]:
# number of qubits
n = 2

n_statevector = np.kron(ket_0, ket_0)
print(n_statevector)

[1 0 0 0]


In [7]:
n_gate_X = np.kron(gate_X, gate_X)
print(n_gate_X)

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


In [8]:
# Hadamard Gate
gate_H = 1/np.sqrt(2)*np.array([[1,1],[1,-1]])
print(gate_H)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [9]:
n_gate_H = np.kron(gate_H, gate_H)
print(n_gate_H)

[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


In [ ]:
def n_kron_product(matrix, n):
    result = matrix
    for i in range(n-1):
        result = np.kron(result, matrix)
    return result

In [56]:
def n_cnot_gate(n):
    dist = n - 2 # number of qubits between control and target qubit (in this case, always first and last qubit)

    sq_X = np.array([[0,1], [1,0]])

    N = 2 ** (dist+2)
    N_half = int(N/2)

    I_half_N = np.identity(N_half)

    Zero_half_N = np.zeros((N_half, N_half))

    I_quarter_N = np.identity(int(N/4))
    right_bottom_matrix = np.kron(I_quarter_N, sq_X)
    
    # print("I_half_N", I_half_N)
    # print("Zero_half_N", Zero_half_N)
    # print("RB", right_bottom_matrix)

    CX = np.block([[I_half_N, Zero_half_N],
                [Zero_half_N, right_bottom_matrix]])

    # print(CX)
    # print(np.kron(I, CX))  
    return CX 

n_cnot = n_cnot_gate(2)
print(n_cnot)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [ ]:
qubits = 10

# Define Single qubit state and gate
sq_ket_0 = np.array([1,0])
sq_ket_1 = np.array([0,1])

sq_I = np.array([[1,0], [0,1]])
sq_X = np.array([[0,1], [1,0]])
sq_H = 1/np.sqrt(2)*np.array([[1,1], [1,-1]])
dq_CNOT = np.array([[1,0,0,0],
                    [0,1,0,0],
                    [0,0,0,1],
                    [0,0,1,0],])


# Define n qubits quantum gates
n_sq_X = n_kron_product(sq_X, qubits)
n_sq_H = n_kron_product(sq_H, qubits)
n_cnot = n_cnot_gate(qubits)

# Define n qubits statevectors
n_statevector = n_kron_product(sq_ket_0, qubits)
print(n_statevector)

result = n_cnot @ n_sq_H @ n_sq_X @ n_statevector

print(result)


NameError: name 'np' is not defined

In [14]:
def apply_x_on_kth_qubit(n, k):
    I = np.array([[1, 0], [0, 1]])
    X = np.array([[0, 1], [1, 0]])
    
    # Initialize the result as identity
    result = 1
    for i in range(n):
        if i == k:
            result = np.kron(result, X)
        else:
            result = np.kron(result, I)
    return result

# Example: Apply X on the 2nd qubit in a 3-qubit system
n = 3
k = 1
x_on_2nd_qubit = apply_x_on_kth_qubit(n, k)
print("X gate on the 2nd qubit in a 3-qubit system:\n", x_on_2nd_qubit)


X gate on the 2nd qubit in a 3-qubit system:
 [[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]


In [18]:
import numpy as np

def cnot_matrix(n, control_qubit, target_qubit):
    # Initialize the CNOT matrix as an identity matrix
    cnot_mat = np.eye(2**n)
    
    # Construct the CNOT matrix
    for i in range(2**n):
        # Convert the index to binary representation
        bin_i = f"{i:0{n}b}"
        # Determine control and target qubit states
        control_state = int(bin_i[control_qubit])
        target_state = int(bin_i[target_qubit])
        
        # If control qubit is |1⟩, flip the target qubit
        if control_state == 1:
            # Flip the target qubit by toggling its state
            new_target_state = 1 - target_state
            # Create new index with the target qubit flipped
            new_bin_i = list(bin_i)
            new_bin_i[target_qubit] = str(new_target_state)
            new_index = int(''.join(new_bin_i), 2)
            
            # Set the corresponding entry in the CNOT matrix
            cnot_mat[i, new_index] = 1
            cnot_mat[new_index, i] = 1  # Ensure symmetry for the two states
    
    return cnot_mat

# Example usage for a 3-qubit CNOT gate
n = 3  # Total qubits
control_qubit = 0  # First qubit as control
target_qubit = 2   # Second qubit as target

cnot_gate = cnot_matrix(n, control_qubit, target_qubit)
print(cnot_gate)


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1.]]


In [20]:
import numpy as np

# Define the matrices for the gates
I = np.array([[1, 0], [0, 1]])  # Identity gate (2x2 matrix)
zero_gate = np.array([[0, 0], [0, 0]])  # Zero gate (2x2 matrix)
X = np.array([[0, 1], [1, 0]])  # Pauli-X gate (2x2 matrix)

# Construct the block matrix A
A = np.block([[I, zero_gate], 
               [zero_gate, X]])

# Display the matrix A in general format
print("Matrix A:")
print(A)

Matrix A:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


Implementation of generalized controlled gate U with n qubits between the control qubit and target qubit:

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[0. 1.]
 [1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
